In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("data/owid-covid-data.csv")

# Preview the first 5 rows
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [2]:
# Display column names
print("ðŸ”‘ Columns in dataset:")
print(df.columns.tolist())

# Check basic info
df.info()

# Summary stats
df.describe()

ðŸ”‘ Columns in dataset:
['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 'stringency_index', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'population', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350085 entries, 0 to 350084
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    350085 non-null  object
 1   continent                                   333420 non-null  object
 2   location                                    350085 non-null  object
 3   date                                        350085 non-null  object
 4   total_cases                                 312088 non-null  float64
 5   new_cases                                   340457 non-null  float64
 6   new_cases_smoothed                          339198 non-null  float64
 7   total_deaths                                290501 non-null  float64
 8   new_deaths                                  340511 non-null  float64
 9   new_deaths_smoothed                         339281 non-null  float64
 10  total_cases_per_million                     312088 non-null  float64
 11  new_cases_per_million                       340457 non-null  float64
 12  new_cases_smoothed_per_million              339198 non-null  float64
 13  total_deaths_per_million                    290501 non-null  float64
 14  new_deaths_per_million                      340511 non-null  float64
 15  new_deaths_smoothed_per_million             339281 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37615 non-null   float64
 18  icu_patients_per_million                    37615 non-null   float64
 19  hosp_patients                               38902 non-null   float64
 20  hosp_patients_per_million                   38902 non-null   float64
 21  weekly_icu_admissions                       10205 non-null   float64
 22  weekly_icu_admissions_per_million           10205 non-null   float64
 23  weekly_hosp_admissions                      23253 non-null   float64
 24  weekly_hosp_admissions_per_million          23253 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          79308 non-null   float64
 35  people_vaccinated                           75911 non-null   float64
 36  people_fully_vaccinated                     72575 non-null   float64
 37  total_boosters                              47562 non-null   float64
 38  new_vaccinations                            65346 non-null   float64
 39  new_vaccinations_smoothed                   180718 non-null  float64
 40  total_vaccinations_per_hundred              79308 non-null   float64
 41  people_vaccinated_per_hundred               75911 non-null   float64
 42  people_fully_vaccinated_per_hundred         72575 non-null   float64
 43  total_boosters_per_hundred                  47562 non-null   float64
 44  new_vaccinations_smoothed_per_million       180718 non-null  float64
 45  new_people_vaccinated_smoothed              180489 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  180489 non-null  float64
 47  stringency_index                            197651 non-null  float64
 48  population_density                          297178 non-null  float64
 49  median_age                                  276367 non-null  float64
 50  aged_65_older                               266708 non-null  float64
 51  aged_70_older                               273597 non-null  float64
 52  gdp_per_capita                              270863 non-null  float64
 53  extreme_poverty                             174561 non-null  float64
 54  cardiovasc_death_rate                       271487 non-null  float64
 55  diabetes_prevalence                         285303 non-null  float64
 56  female_smokers                              203659 non-null  float64
 57  male_smokers                                200889 non-null  float64
 58  handwashing_facilities                      132973 non-null  float64
 59  hospital_beds_per_thousand                  239669 non-null  float64
 60  life_expectancy                             322072 non-null  float64
 61  human_development_index                     263138 non-null  float64
 62  population                                  350085 non-null  float64
 63  excess_mortality_cumulative_absolute        12184 non-null   float64
 64  excess_mortality_cumulative                 12184 non-null   float64
 65  excess_mortality                            12184 non-null   float64
 66  excess_mortality_cumulative_per_million     12184 non-null   float64
dtypes: float64(62), object(5)
memory usage: 179.0+ MB

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,3.120880e+05,3.404570e+05,3.391980e+05,2.905010e+05,340511.000000,339281.000000,312088.000000,340457.000000,339198.000000,290501.000000,...,200889.000000,132973.000000,239669.000000,322072.000000,263138.000000,3.500850e+05,1.218400e+04,12184.000000,12184.000000,12184.000000
mean,6.683354e+06,9.601634e+03,9.637066e+03,8.602180e+04,85.511055,85.817071,101749.851259,145.163814,145.696924,872.289356,...,32.909483,50.789962,3.097245,73.713631,0.722464,1.284633e+08,5.281637e+04,9.738648,11.345256,1669.025575
std,4.068903e+07,1.102769e+05,9.447784e+04,4.398873e+05,613.687971,559.130004,151265.689121,1163.714678,599.957847,1100.189784,...,13.573767,31.956100,2.548327,7.395220,0.148976,6.607694e+08,1.492195e+05,12.304441,25.181297,1938.556228
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2752.924800
25%,8.090000e+03,0.000000e+00,2.860000e-01,1.270000e+02,0.000000,0.000000,2595.577500,0.000000,0.044000,60.606000,...,22.600000,20.859000,1.300000,69.590000,0.602000,4.490020e+05,1.202250e+02,1.400000,-1.600000,72.395046
50%,7.020500e+04,2.000000e+00,2.485700e+01,1.328000e+03,0.000000,0.143000,28307.659000,0.128000,6.517000,377.169000,...,33.100000,49.839000,2.500000,75.050000,0.740000,5.882259e+06,5.885850e+03,8.075000,5.720000,1105.404700
75%,7.409558e+05,2.640000e+02,4.978570e+02,1.192200e+04,3.000000,5.143000,133506.244000,35.466000,82.411000,1365.925000,...,41.300000,82.502000,4.200000,79.460000,0.829000,2.830170e+07,3.742344e+04,15.360000,16.302500,2740.130200
max,7.714071e+08,8.401961e+06,6.402036e+06,6.972139e+06,27939.000000,14822.000000,737554.506000,228872.025000,37241.781000,6511.209000,...,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,1.289776e+06,76.620000,377.630000,10292.916000

In [3]:
# Count missing values per column
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values[missing_values > 0]

weekly_icu_admissions                   339880
weekly_icu_admissions_per_million       339880
excess_mortality                        337901
excess_mortality_cumulative_absolute    337901
excess_mortality_cumulative             337901
                                         ...
new_deaths_smoothed                      10804
new_cases                                 9628
new_cases_per_million                     9628
new_deaths                                9574
new_deaths_per_million                    9574
Length: 63, dtype: int64

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
selected_countries = ['Kenya', 'United States', 'India']
df_filtered = df[df['location'].isin(selected_countries)].copy()